tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "awscli"
brew "cmake"
brew "reattach-to-user-namespace"
brew "n" # node version management
brew "stow"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "z"
brew "zsh"
cask "docker"
cask "postman"
